### ISSUE TITLE
Issue of Unknow Host

### ISSUE THREAD

**Issue by anki1427** [axcl/SMACK-API-Android-Demo#3]
Hello,
I am using Smack API for communicating with Ejabberd server for chatting. My Ejabberd server is hosted over domain name i.e:- "dev.oodlesbit.in". 
I am getting Unknown host exception while calling the connect method of smack API.
Putting DOMAIN-"dev.oodlesbit.in" and HOST - "dev.oodlesbit.in". Just wondering to know that should I need to put the domain name in Domain and subdomain name in case of Host or we can use same in both DOMAIN and HOST. As I see in the example of SMACK-API_ANDROID_DEMO.

Would appreciate if you please help me regarding this issue.

`Connection closed with error
                                                                             org.jivesoftware.smack.XMPPException$StreamErrorException: host-unknown You can read more about the meaning of this stream error at http://xmpp.org/rfcs/rfc6120.html#streams-error-conditions
                                                                             <stream:error><host-unknown xmlns='urn:ietf:params:xml:ns:xmpp-streams'/></stream:error>
                                                                                 at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketReader.parsePackets(XMPPTCPConnection.java:1003)  at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketReader.access$300(XMPPTCPConnection.java:944)
                                                                                 at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketReader$1.run(XMPPTCPConnection.java:959)
                                                                                 at java.lang.Thread.run(Thread.java:761)`

Any help would be appreciated.

Thanks

**Comment by cbedoy** [comment]
I have the same issue

**Comment by axcl** [comment]
It seems like your server is not receiving request on the xmpp 5222 port

**Comment by axcl** [comment]
You can check if server is recieving request on the xmpp port or not using telnet

**Comment by jasprv** [comment]
Having the same issue here. Server works, other xmpp apps on the same device work.
